config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :loras
  resources :renders
  resources :images
  resources :models do
    resources :fine_tunes, only: [:index, :new, :create]
  end

  resources :fine_tunes, only: [:show, :edit, :update, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
  root "renders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fine_tune.rb
class FineTune < ApplicationRecord
  belongs_to :model
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :render
  has_one_attached :image
end

app/models/lora.rb
class Lora < ApplicationRecord
  belongs_to :model
  has_many :render_loras, class_name: "RenderLora", dependent: :nullify
  has_many :renders, through: :render_loras

  scope :replicate, -> { where(platform: "Replicate") }
  scope :civitai, -> { where(platform: "Civitai") }
  scope :hugging_face, -> { where(platform: "Hugging Face")}
end

app/models/model.rb
class Model < ApplicationRecord
  has_many :renders, dependent: :nullify
  has_many :render_loras, through: :renders
  has_many :loras
  has_many :fine_tunes

  validates :name, :company, :platform, :platform_source, presence: true

  scope :replicate, -> { where(platform: "Replicate") }
  scope :civitai, -> { where(platform: "Civitai") }
  scope :hugging_face, -> { where(platform: "Hugging Face")}
end

app/models/render.rb
class Render < ApplicationRecord
  belongs_to :model
  has_many :render_loras, dependent: :destroy
  has_many :loras, through: :render_loras
  has_many :images, dependent: :destroy

  validates :guidance_scale, presence: true, numericality: { greater_than: 0 }
  validates :prompt, presence: true

  has_one_attached :file

  accepts_nested_attributes_for :render_loras, allow_destroy: true
end

app/models/render_lora.rb
class RenderLora < ApplicationRecord
  belongs_to :render
  belongs_to :lora
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :model

  has_one_attached :zip_file
  has_one_attached :model_weights

  validates :steps, :lora_rank, :optimizer, :trigger_word, presence: true
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @pagy, @models = pagy(Model.all)
    @fine_tunes = FineTune.includes(:model)
  end

  # GET /models/1 or /models/1.json
  def show
    @model = Model.find(params[:id])
    @fine_tunes = FineTune.includes(:model)
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy!

    respond_to do |format|
      format.html { redirect_to models_path, status: :see_other, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:name, :platform, :platform_source, :platform_link, :company)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_with(model: model, class: "contents") do |form| %>
  <% if model.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "text-white" %>
    <%= form.text_area :name, rows: 1, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :company, class: "text-white" %>
    <%= form.text_area :company, rows: 1, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :platform, "Platform", class: "text-white" %>
    <%= form.select :platform, options_for_select(['Replicate', 'Civitai', 'Hugging Face']), class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :platform_source, class: "text-white" %>
    <%= form.text_area :platform_source, rows: 1, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :platform_link, class: "text-white" %>
    <%= form.text_area :platform_link, rows: 1, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div class="text-white">
  <div class="mx-2 my-2">
    <%= link_to model.name, models_path %>
  </div>

  <div class="mx-2">
    <strong class="mb-1 font-medium">Platform Source:</strong>
    <%= model.platform_source %>
  </div>

  <div class="mx-2">
    <strong class="mb-1 font-medium">Fine Tunes:</strong>
    <% @fine_tunes.each do |fine_tune| %>
      <%= fine_tune.name %>
    <% end %>
  </div>
</div>

app/views/models/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-white">Editing model</h1>

  <%= render "form", model: @model %>

  <%= link_to "Show this model", @model, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to models", models_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/models/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Models" %>
  <h1 class="text-4xl font-bold text-white">Models</h1>

  <%= render partial: "shared/resource_table", locals: { 
    collection: @models,
    fine_tunes: @fine_tunes,
    headers: [
      { label: "Name", basis: "1/5", content: ->(model) { link_to model.name, model_path(model) } },
      { label: "", basis: "1/5", content: -> (model){
        link_to "Fine Tunes (#{@fine_tunes.size})", "#" ,
          class: "text-left",
          data: { action: "fine-tune#handleClick" }
        }
      },
      { label: "Company", basis: "1/5", content: ->(model) { model.company } },
      { label: "Platform", basis: "1/5", content: ->(model) { model.platform } },
      { label: "Source", basis: "1/5", content: ->(model) { link_to "Link", model.platform_link }, class: "text-center" }
    ],
  }%>
</div>

<!-- Pagy Navigation Links -->
<div class="flex justify-between">
  <div class="mt-4 text-white">
    <%== pagy_nav(@pagy) %>
  </div>

  <div class="text-white ">
    <%= link_to "New model", new_model_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
</div>

app/views/models/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-white">New model</h1>

  <%= render "form", model: @model %>

  <%= link_to "Back to models", models_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/models/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <%= render @model %>

    <%= link_to "Edit this model", edit_model_path(@model), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to models", models_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this model", @model, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Add Fine Tune", new_model_fine_tune_path(@model), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/models/show.turbo_stream.erb
<%= turbo_stream.replace dom_id(@model) do %>
  <%= render @model %>
<% end %>