config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :loras
  resources :renders
  resources :images
  resources :models do
    resources :fine_tunes, only: [:index, :new, :create]
  end

  resources :fine_tunes, only: [:show, :edit, :update, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
  root "renders#index"
end

app/models/lora.rb
class Lora < ApplicationRecord
  belongs_to :model
  has_many :render_loras, class_name: "RenderLora", dependent: :nullify
  has_many :renders, through: :render_loras

  scope :replicate, -> { where(platform: "Replicate") }
  scope :civitai, -> { where(platform: "Civitai") }
  scope :hugging_face, -> { where(platform: "Hugging Face")}
end

app/controllers/loras_controller.rb
class LorasController < ApplicationController
  before_action :set_lora, only: %i[ show edit update destroy ]

  # GET /loras or /loras.json
  def index
    @loras = Lora.all
    @models = Model.all
    @sort = [:name, :trigger, :platform, :model_id]
    @filters = [:platform, :model_id]
    @filter_options = {}
    # Take filter symbols, iterate and 
    @filter_options = get_filter_options(@filters, @filter_options, Lora)

    # Sort Loras
    @loras = sorted_records(@loras, params[:sort_by], @sort)
    @loras = apply_filter_conditions(@filters, params, @loras)

    @pagy, @loras = pagy(@loras)

    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "loras_table", 
          partial: "shared/resource_table",
          locals: { 
            collection: @loras, 
            headers: view_context.loras_table_headers
          }
        )
      end
    end
  end

  # GET /loras/1 or /loras/1.json
  def show
  end

  # GET /loras/new
  def new
    @lora = Lora.new
    @models = Model.all
  end

  # GET /loras/1/edit
  def edit
    @lora = Lora.find(params[:id])
    @models = Model.all
  end

  # POST /loras or /loras.json
  def create
    @lora = Lora.new(lora_params)

    respond_to do |format|
      if @lora.save
        format.html { redirect_to @lora, notice: "Lora was successfully created." }
        format.json { render :show, status: :created, location: @lora }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loras/1 or /loras/1.json
  def update
    respond_to do |format|
      if @lora.update(lora_params)
        format.html { redirect_to @lora, notice: "Lora was successfully updated." }
        format.json { render :show, status: :ok, location: @lora }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loras/1 or /loras/1.json
  def destroy
    @lora.destroy!

    respond_to do |format|
      format.html { redirect_to loras_path, status: :see_other, notice: "Lora was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lora
    @lora = Lora.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lora_params
    params.require(:lora).permit(:name, :url_src, :platform, :trigger, :model_id, :platform_url)
  end

  def sorting_params
    params[:sort_by] || "name"
  end
end

app/helpers/loras_helper.rb
module LorasHelper
end

app/views/loras/_form.html.erb
<%= form_with(model: lora, class: "contents") do |form| %>
  <% if lora.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(lora.errors.count, "error") %> prohibited this lora from being saved:</h2>

      <ul>
        <% lora.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name , class: "text-white" %>
    <%= form.text_area :name, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url_src, "URL Source", class: "text-white" %>
    <%= form.text_area :url_src, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :trigger, class: "text-white" %>
    <%= form.text_area :trigger, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.collection_select :model_id, @models, :id, :name, { prompt: "Select a Model" }, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Platform:", class: "text-white" %>
    <%= form.select :platform, options_for_select(['Replicate', 'Civitai', 'Hugging Face']), class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :platform_url, "Platform URL:", class: "text-white" %>
    <%= form.text_area :platform_url, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/loras/_lora.html.erb
<div class="flex text-white border-b border-gray-200">
  <div class="p-2 basis-1/5">
    <%= lora.name %>
  </div>

  <div class="p-2 basis-1/5">
    <%= lora.url_src %>
  </div>

  <div class="p-2 basis-1/5">
    <%= lora.trigger %>
  </div>

  <div class="p-2 basis-1/5">
    <%= lora.platform %>
  </div>

  <div class="p-2 basis-1/5">
    <%= link_to model_path(lora.model) do %>
      <%= lora.model.name %>
    <% end %>
  </div>
</div>

app/views/loras/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lora</h1>

  <%= render "form", lora: @lora %>

  <%= link_to "Show this lora", @lora, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to loras", loras_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/loras/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Loras" %>

  <div class="flex items-center justify-between text-white">
    <h1 class="text-4xl font-bold">Loras</h1>
    <%= link_to "New lora", new_lora_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <!-- Sort Button -->
  <%= render partial: "shared/sort_table", locals: {
    collection: @loras,
    sortables: @sort,
    resource_name: :loras
  } %>

  <!-- Filter List -->
  <div>
    <%= render partial: "shared/filter_options", locals: {
      collection: @loras,
      filters: @filters,
      resource_name: :loras
    } %>
  </div>

  <!-- Pagy Navigation Links -->
  <div class="flex justify-center">
    <div class="mt-4 text-white">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>

  <!-- Loras Table -->
  <%= turbo_frame_tag "loras_table" do %>
    <%= render partial: "shared/resource_table", locals: { 
      collection: @loras, 
      headers: loras_table_headers
    } %>
  <% end %>
</div>

app/views/loras/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-white">New lora</h1>

  <%= render "form", lora: @lora %>

  <%= link_to "Back to loras", loras_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/loras/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @lora %>

    <%= link_to "Edit this lora", edit_lora_path(@lora), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to loras", loras_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this lora", @lora, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>