config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :loras
  resources :renders
  resources :images
  resources :models do
    resources :fine_tunes, only: [:index, :new, :create]
  end

  resources :fine_tunes, only: [:show, :edit, :update, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
  root "renders#index"
end

app/models/fine_tune.rb
class FineTune < ApplicationRecord
  belongs_to :model
end

app/controllers/fine_tunes_controller.rb
class FineTunesController < ApplicationController
  before_action :set_fine_tune, only: %i[ show edit update destroy ]
  before_action :set_models

  # GET /fine_tunes or /fine_tunes.json
  def index
    @model = Model.find(params[:model_id])
    @fine_tunes = @model.fine_tunes
  end

  # GET /fine_tunes/1 or /fine_tunes/1.json
  def show
    @fine_tune = FineTune.find(params[:id])
    @model = @fine_tune.model
  end

  # GET /fine_tunes/new
  def new
    @model = Model.find(params[:model_id])
    @fine_tune = @model.fine_tunes.build
    @platforms = @models.map { |model| model.platform }.uniq
  end

  # GET /fine_tunes/1/edit
  def edit
  end

  # POST /fine_tunes or /fine_tunes.json
  def create
    @fine_tune = FineTune.new(fine_tune_params)

    respond_to do |format|
      if @fine_tune.save
        format.html { redirect_to @fine_tune, notice: "Fine tune was successfully created." }
        format.json { render :show, status: :created, location: @fine_tune }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fine_tune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fine_tunes/1 or /fine_tunes/1.json
  def update
    respond_to do |format|
      if @fine_tune.update(fine_tune_params)
        format.html { redirect_to @fine_tune, notice: "Fine tune was successfully updated." }
        format.json { render :show, status: :ok, location: @fine_tune }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fine_tune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fine_tunes/1 or /fine_tunes/1.json
  def destroy
    @fine_tune.destroy!

    respond_to do |format|
      format.html { redirect_to fine_tunes_path, status: :see_other, notice: "Fine tune was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine_tune
      @fine_tune = FineTune.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fine_tune_params
      params.require(:fine_tune).permit(:name, :platform, :platform_source, :platform_link, :model_id)
    end

    def set_models
      @models = Model.all
    end
end

app/helpers/fine_tunes_helper.rb
module FineTunesHelper
end

app/views/fine_tunes/_fine_tune.html.erb
<div id="<%= dom_id fine_tune %>">
  <p class="my-5 text-white">
    <strong class="block mb-1 font-medium">Name:</strong>
    <%= fine_tune.name %>
  </p>

  <p class="my-5 text-white">
    <strong class="block mb-1 font-medium">Platform:</strong>
    <%= fine_tune.platform %>
  </p>

  <p class="my-5 text-white">
    <strong class="block mb-1 font-medium">Platform source:</strong>
    <%= fine_tune.platform_source %>
  </p>

  <p class="my-5 text-white">
    <strong class="block mb-1 font-medium">Platform link:</strong>
    <%= fine_tune.platform_link %>
  </p>
</div>

app/views/fine_tunes/_form.html.erb
<%= form_with(model: [model, fine_tune], class: "contents") do |form| %>
  <% if fine_tune.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(fine_tune.errors.count, "error") %> prohibited this fine_tune from being saved:</h2>

      <ul>
        <% fine_tune.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :model_id, value: model.id %>

  <div class="my-5">
    <%= form.label :name, class: "text-white" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.select :platform, @platforms, 
      { prompt: "Select a Platform" }, 
      { class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.label :platform_source, class: "text-white" %>
    <%= form.text_field :platform_source, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :platform_link, class: "text-white" %>
    <%= form.text_field :platform_link, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/fine_tunes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing fine tune</h1>

  <%= render "form", fine_tune: @fine_tune %>

  <%= link_to "Show this fine tune", @fine_tune, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to fine tunes", fine_tunes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fine_tunes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Fine tunes" %>

  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold text-white">Fine Tunes for <%= @model.name %></h1>
    <%= link_to "New fine tune", new_model_fine_tune_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= render partial: "shared/resource_table", locals: { 
    collection: @fine_tunes, 
    headers: [
      { label: "Name", basis: "1/4", content: ->(fine_tune) { fine_tune.name } },
      { label: "Platform", basis: "1/4", content: ->(fine_tune) { fine_tune.platform } },
      { label: "Platform Link", basis: "1/4", content: ->(fine_tune) { fine_tune.platform_link } },
      { label: "Source", basis: "1/4", content: ->(fine_tune) { link_to "source", fine_tune.platform_source }, class: "text-center" }
    ],
  }%>
</div>

app/views/fine_tunes/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-white">New fine tune</h1>

  <%= render "form", model: @model, fine_tune: @fine_tune %>

  <%= link_to "Back to fine tunes", model_fine_tunes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/fine_tunes/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <%= render @fine_tune %>

    <%= link_to "Edit this fine tune", edit_fine_tune_path(@fine_tune), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to fine tunes", model_fine_tunes_path(@fine_tune), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this fine tune", @fine_tune, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>